---
language: node_js
node_js:
- lts/*
dist: xenial
services:
- xvfb
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.
script:
  - npm run lint
  - npm run test:unit
#  - xvfb-run -e /dev/stdout --server-args="-screen 0 1024x768x24" -a npm run test:e2e:travis
